# Generated by Django 4.0 on 2021-12-21 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='firstname',
        ),
    ]
