# Generated by Django 4.0 on 2021-12-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud1', '0002_remove_information_firstname'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='firstname',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
